/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.dm.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Dm_suibi_list implements org.apache.thrift.TBase<Dm_suibi_list, Dm_suibi_list._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Dm_suibi_list");

  private static final org.apache.thrift.protocol.TField IS_SUCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("isSucess", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField SBLIST_FIELD_DESC = new org.apache.thrift.protocol.TField("sblist", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField PAGEPARM_FIELD_DESC = new org.apache.thrift.protocol.TField("pageparm", org.apache.thrift.protocol.TType.STRUCT, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new Dm_suibi_listStandardSchemeFactory());
    schemes.put(TupleScheme.class, new Dm_suibi_listTupleSchemeFactory());
  }

  public boolean isSucess; // required
  public String message; // required
  public List<Dm_suibi> sblist; // required
  public Pageparm pageparm; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    IS_SUCESS((short)1, "isSucess"),
    MESSAGE((short)2, "message"),
    SBLIST((short)3, "sblist"),
    PAGEPARM((short)4, "pageparm");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // IS_SUCESS
          return IS_SUCESS;
        case 2: // MESSAGE
          return MESSAGE;
        case 3: // SBLIST
          return SBLIST;
        case 4: // PAGEPARM
          return PAGEPARM;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ISSUCESS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.IS_SUCESS, new org.apache.thrift.meta_data.FieldMetaData("isSucess", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SBLIST, new org.apache.thrift.meta_data.FieldMetaData("sblist", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Dm_suibi.class))));
    tmpMap.put(_Fields.PAGEPARM, new org.apache.thrift.meta_data.FieldMetaData("pageparm", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Pageparm.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Dm_suibi_list.class, metaDataMap);
  }

  public Dm_suibi_list() {
  }

  public Dm_suibi_list(
    boolean isSucess,
    String message,
    List<Dm_suibi> sblist,
    Pageparm pageparm)
  {
    this();
    this.isSucess = isSucess;
    setIsSucessIsSet(true);
    this.message = message;
    this.sblist = sblist;
    this.pageparm = pageparm;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Dm_suibi_list(Dm_suibi_list other) {
    __isset_bitfield = other.__isset_bitfield;
    this.isSucess = other.isSucess;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetSblist()) {
      List<Dm_suibi> __this__sblist = new ArrayList<Dm_suibi>();
      for (Dm_suibi other_element : other.sblist) {
        __this__sblist.add(new Dm_suibi(other_element));
      }
      this.sblist = __this__sblist;
    }
    if (other.isSetPageparm()) {
      this.pageparm = new Pageparm(other.pageparm);
    }
  }

  public Dm_suibi_list deepCopy() {
    return new Dm_suibi_list(this);
  }

  @Override
  public void clear() {
    setIsSucessIsSet(false);
    this.isSucess = false;
    this.message = null;
    this.sblist = null;
    this.pageparm = null;
  }

  public boolean isIsSucess() {
    return this.isSucess;
  }

  public Dm_suibi_list setIsSucess(boolean isSucess) {
    this.isSucess = isSucess;
    setIsSucessIsSet(true);
    return this;
  }

  public void unsetIsSucess() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ISSUCESS_ISSET_ID);
  }

  /** Returns true if field isSucess is set (has been assigned a value) and false otherwise */
  public boolean isSetIsSucess() {
    return EncodingUtils.testBit(__isset_bitfield, __ISSUCESS_ISSET_ID);
  }

  public void setIsSucessIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ISSUCESS_ISSET_ID, value);
  }

  public String getMessage() {
    return this.message;
  }

  public Dm_suibi_list setMessage(String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  public int getSblistSize() {
    return (this.sblist == null) ? 0 : this.sblist.size();
  }

  public java.util.Iterator<Dm_suibi> getSblistIterator() {
    return (this.sblist == null) ? null : this.sblist.iterator();
  }

  public void addToSblist(Dm_suibi elem) {
    if (this.sblist == null) {
      this.sblist = new ArrayList<Dm_suibi>();
    }
    this.sblist.add(elem);
  }

  public List<Dm_suibi> getSblist() {
    return this.sblist;
  }

  public Dm_suibi_list setSblist(List<Dm_suibi> sblist) {
    this.sblist = sblist;
    return this;
  }

  public void unsetSblist() {
    this.sblist = null;
  }

  /** Returns true if field sblist is set (has been assigned a value) and false otherwise */
  public boolean isSetSblist() {
    return this.sblist != null;
  }

  public void setSblistIsSet(boolean value) {
    if (!value) {
      this.sblist = null;
    }
  }

  public Pageparm getPageparm() {
    return this.pageparm;
  }

  public Dm_suibi_list setPageparm(Pageparm pageparm) {
    this.pageparm = pageparm;
    return this;
  }

  public void unsetPageparm() {
    this.pageparm = null;
  }

  /** Returns true if field pageparm is set (has been assigned a value) and false otherwise */
  public boolean isSetPageparm() {
    return this.pageparm != null;
  }

  public void setPageparmIsSet(boolean value) {
    if (!value) {
      this.pageparm = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case IS_SUCESS:
      if (value == null) {
        unsetIsSucess();
      } else {
        setIsSucess((Boolean)value);
      }
      break;

    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((String)value);
      }
      break;

    case SBLIST:
      if (value == null) {
        unsetSblist();
      } else {
        setSblist((List<Dm_suibi>)value);
      }
      break;

    case PAGEPARM:
      if (value == null) {
        unsetPageparm();
      } else {
        setPageparm((Pageparm)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case IS_SUCESS:
      return Boolean.valueOf(isIsSucess());

    case MESSAGE:
      return getMessage();

    case SBLIST:
      return getSblist();

    case PAGEPARM:
      return getPageparm();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case IS_SUCESS:
      return isSetIsSucess();
    case MESSAGE:
      return isSetMessage();
    case SBLIST:
      return isSetSblist();
    case PAGEPARM:
      return isSetPageparm();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Dm_suibi_list)
      return this.equals((Dm_suibi_list)that);
    return false;
  }

  public boolean equals(Dm_suibi_list that) {
    if (that == null)
      return false;

    boolean this_present_isSucess = true;
    boolean that_present_isSucess = true;
    if (this_present_isSucess || that_present_isSucess) {
      if (!(this_present_isSucess && that_present_isSucess))
        return false;
      if (this.isSucess != that.isSucess)
        return false;
    }

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_sblist = true && this.isSetSblist();
    boolean that_present_sblist = true && that.isSetSblist();
    if (this_present_sblist || that_present_sblist) {
      if (!(this_present_sblist && that_present_sblist))
        return false;
      if (!this.sblist.equals(that.sblist))
        return false;
    }

    boolean this_present_pageparm = true && this.isSetPageparm();
    boolean that_present_pageparm = true && that.isSetPageparm();
    if (this_present_pageparm || that_present_pageparm) {
      if (!(this_present_pageparm && that_present_pageparm))
        return false;
      if (!this.pageparm.equals(that.pageparm))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(Dm_suibi_list other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    Dm_suibi_list typedOther = (Dm_suibi_list)other;

    lastComparison = Boolean.valueOf(isSetIsSucess()).compareTo(typedOther.isSetIsSucess());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsSucess()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isSucess, typedOther.isSucess);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMessage()).compareTo(typedOther.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, typedOther.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSblist()).compareTo(typedOther.isSetSblist());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSblist()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sblist, typedOther.sblist);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPageparm()).compareTo(typedOther.isSetPageparm());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPageparm()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pageparm, typedOther.pageparm);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Dm_suibi_list(");
    boolean first = true;

    sb.append("isSucess:");
    sb.append(this.isSucess);
    first = false;
    if (!first) sb.append(", ");
    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sblist:");
    if (this.sblist == null) {
      sb.append("null");
    } else {
      sb.append(this.sblist);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("pageparm:");
    if (this.pageparm == null) {
      sb.append("null");
    } else {
      sb.append(this.pageparm);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (pageparm != null) {
      pageparm.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class Dm_suibi_listStandardSchemeFactory implements SchemeFactory {
    public Dm_suibi_listStandardScheme getScheme() {
      return new Dm_suibi_listStandardScheme();
    }
  }

  private static class Dm_suibi_listStandardScheme extends StandardScheme<Dm_suibi_list> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Dm_suibi_list struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // IS_SUCESS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.isSucess = iprot.readBool();
              struct.setIsSucessIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // SBLIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list192 = iprot.readListBegin();
                struct.sblist = new ArrayList<Dm_suibi>(_list192.size);
                for (int _i193 = 0; _i193 < _list192.size; ++_i193)
                {
                  Dm_suibi _elem194; // required
                  _elem194 = new Dm_suibi();
                  _elem194.read(iprot);
                  struct.sblist.add(_elem194);
                }
                iprot.readListEnd();
              }
              struct.setSblistIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PAGEPARM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.pageparm = new Pageparm();
              struct.pageparm.read(iprot);
              struct.setPageparmIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Dm_suibi_list struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(IS_SUCESS_FIELD_DESC);
      oprot.writeBool(struct.isSucess);
      oprot.writeFieldEnd();
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      if (struct.sblist != null) {
        oprot.writeFieldBegin(SBLIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.sblist.size()));
          for (Dm_suibi _iter195 : struct.sblist)
          {
            _iter195.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.pageparm != null) {
        oprot.writeFieldBegin(PAGEPARM_FIELD_DESC);
        struct.pageparm.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class Dm_suibi_listTupleSchemeFactory implements SchemeFactory {
    public Dm_suibi_listTupleScheme getScheme() {
      return new Dm_suibi_listTupleScheme();
    }
  }

  private static class Dm_suibi_listTupleScheme extends TupleScheme<Dm_suibi_list> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Dm_suibi_list struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIsSucess()) {
        optionals.set(0);
      }
      if (struct.isSetMessage()) {
        optionals.set(1);
      }
      if (struct.isSetSblist()) {
        optionals.set(2);
      }
      if (struct.isSetPageparm()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetIsSucess()) {
        oprot.writeBool(struct.isSucess);
      }
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
      if (struct.isSetSblist()) {
        {
          oprot.writeI32(struct.sblist.size());
          for (Dm_suibi _iter196 : struct.sblist)
          {
            _iter196.write(oprot);
          }
        }
      }
      if (struct.isSetPageparm()) {
        struct.pageparm.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Dm_suibi_list struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.isSucess = iprot.readBool();
        struct.setIsSucessIsSet(true);
      }
      if (incoming.get(1)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list197 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.sblist = new ArrayList<Dm_suibi>(_list197.size);
          for (int _i198 = 0; _i198 < _list197.size; ++_i198)
          {
            Dm_suibi _elem199; // required
            _elem199 = new Dm_suibi();
            _elem199.read(iprot);
            struct.sblist.add(_elem199);
          }
        }
        struct.setSblistIsSet(true);
      }
      if (incoming.get(3)) {
        struct.pageparm = new Pageparm();
        struct.pageparm.read(iprot);
        struct.setPageparmIsSet(true);
      }
    }
  }

}

